-- ============================================================================
-- Antwerp Unseen — Supabase schema
-- Run this in the Supabase dashboard: SQL Editor -> New query -> paste -> Run.
-- Safe to re-run: uses IF NOT EXISTS / DROP POLICY IF EXISTS where possible.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- submissions: every contribution made through the /submit flow
-- ----------------------------------------------------------------------------
create table if not exists public.submissions (
                                                  id            bigint generated by default as identity primary key,
                                                  created_at    timestamptz not null default now(),

    location      text,                 -- installation slug from the QR (?location=)
    prompt_id     integer,              -- which prompt was answered (?prompt=)
    prompt_text   text,                 -- the prompt text, stored for traceability
    format        text not null,        -- 'text' | 'voice' | 'image' | 'video'
    user_type     text,                 -- e.g. 'local' | 'tourist'
    content_text  text,                 -- the message (text submissions)
    file_url      text,                 -- public URL of uploaded media (voice/image/video)
    file_name     text                  -- original file name
    );

-- helpful index for the archive / installation (newest first)
create index if not exists submissions_created_at_idx
    on public.submissions (created_at desc);

-- ----------------------------------------------------------------------------
-- artworks: curated images for the artists archive (optional)
-- ----------------------------------------------------------------------------
create table if not exists public.artworks (
                                               id          bigint generated by default as identity primary key,
                                               created_at  timestamptz not null default now(),
    title       text,
    artist      text,
    image_url   text
    );

-- ============================================================================
-- Row Level Security
-- The app uses the public anon key in the browser, so we must explicitly allow
-- anonymous visitors to insert submissions and to read both tables.
-- ============================================================================

alter table public.submissions enable row level security;
alter table public.artworks    enable row level security;

-- Anyone may read submissions (archive + installation display)
drop policy if exists "submissions: public read" on public.submissions;
create policy "submissions: public read"
    on public.submissions for select
                                              to anon, authenticated
                                              using (true);

-- Anyone may create a submission (the public contribution flow)
drop policy if exists "submissions: public insert" on public.submissions;
create policy "submissions: public insert"
    on public.submissions for insert
    to anon, authenticated
    with check (true);

-- Anyone may read artworks
drop policy if exists "artworks: public read" on public.artworks;
create policy "artworks: public read"
    on public.artworks for select
                                                       to anon, authenticated
                                                       using (true);

-- ============================================================================
-- Realtime
-- Required so the installation page updates live as submissions arrive.
-- (You may also need to enable replication for this table in
--  Database -> Replication if it is not picked up automatically.)
-- ============================================================================
alter publication supabase_realtime add table public.submissions;

-- Optional: makes DELETE events carry the removed row's id, so the installation
-- can remove a card live when a submission is deleted.
alter table public.submissions replica identity full;

-- ============================================================================
-- Storage
-- The app uploads voice/image/video to a PUBLIC bucket named "submissions".
-- Create it in the dashboard (Storage -> New bucket -> name "submissions",
-- mark it Public). If you prefer SQL, you can also run:
-- ----------------------------------------------------------------------------
-- insert into storage.buckets (id, name, public)
--   values ('submissions', 'submissions', true)
--   on conflict (id) do nothing;
--
-- And allow public uploads/reads on that bucket:
-- ----------------------------------------------------------------------------
-- drop policy if exists "submissions bucket: public read" on storage.objects;
-- create policy "submissions bucket: public read"
--   on storage.objects for select
--   to anon, authenticated
--   using (bucket_id = 'submissions');
--
-- drop policy if exists "submissions bucket: public upload" on storage.objects;
-- create policy "submissions bucket: public upload"
--   on storage.objects for insert
--   to anon, authenticated
--   with check (bucket_id = 'submissions');
-- ============================================================================